char *words[] = {
    "MAISON", "JARDIN", "VOITURE", "CAMION", "ANIMAL", "TABLE", "CHAISE", "ORDINATEUR", "MONTRE", "LIVRE",
    "FLEUR", "POMME", "BOUTON", "VESTE", "CHAUSSURE", "SOLEIL", "NUAGE", "PLUIE", "LUMIERE", "ECOLE",
    "ARBRE", "ROUTE", "FENETRE", "PORTE", "BATEAU", "COUTEAU", "FOURCHETTE", "CUILLERE", "VERRE", "ASSIETTE",
    "CHIEN", "CHAT", "OISEAU", "POISSON", "FRUIT", "LEGUME", "TOMATE", "PATATE", "CAROTTE", "BIJOU",
    "CLOCHE", "MUR", "PLAFOND", "SOL", "PAPIER", "STYLO", "LIGNE", "POINT", "ETAGERE", "CARTON"
};

int word_length = 50;
