char *words[] = {
    "APPLE", "SHADOW", "TIGER", "BRICK", "LUCKY", "FOREST", "CACTUS", "ROCKET", "BANANA", "MAGNET",
    "WIZARD", "JELLY", "MONKEY", "PIRATE", "ZIPPER", "SILVER", "LLAMA", "COOKIE", "ORANGE", "ROBOT",
    "BUTTON", "DRAGON", "NINJA", "TUNNEL", "KITTEN", "PEBBLE", "SUNSET", "SPIDER", "MARBLE", "ANCHOR",
    "PLANET", "SLIPPER", "HELMET", "NEON", "ECHO", "SPOON", "CIRCUS", "TURTLE", "ICICLE", "PILLOW",
    "CRYSTAL", "MIRROR", "CLOUD", "BASKET", "LANTERN", "BUBBLE", "RIBBON", "CANDLE", "GARDEN", "SHADOW"
};

int word_length = 50;
